# ── Auto-generated by Android Gradle Plugin ────────────────────
# Flutter references Play Core split-install internally but this
# app does not use dynamic delivery, so suppress all warnings.
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task

# ── Flutter & Dart ─────────────────────────────────────────────
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }
-keep class io.flutter.embedding.** { *; }

# ── Bluetooth Serial ───────────────────────────────────────────
-keep class com.github.edufolly.flutterbluetoothserial.** { *; }
-dontwarn com.github.edufolly.**

# ── Drift / SQLite ─────────────────────────────────────────────
-keep class com.tekartik.sqflite.** { *; }
-keep class ** extends androidx.sqlite.db.SupportSQLiteOpenHelper { *; }
-dontwarn org.sqlite.**

# ── Prevent stripping of reflection-accessed classes ───────────
-keepattributes Signature
-keepattributes *Annotation*
-keepattributes SourceFile,LineNumberTable
-keepattributes Exceptions,InnerClasses

# ── AndroidX & Material ────────────────────────────────────────
-keep class androidx.** { *; }
-dontwarn androidx.**

# ── File Picker ────────────────────────────────────────────────
-keep class com.mr.flutter.plugin.filepicker.** { *; }

# ── Share Plus ─────────────────────────────────────────────────
-keep class dev.fluttercommunity.plus.share.** { *; }

# ── Google Fonts (loaded from assets, no reflection needed) ────
-dontwarn com.google.fonts.**

# ── Kotlin coroutines ──────────────────────────────────────────
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**
